### ISSUE TITLE
Complexity analysis

### ISSUE THREAD

**Issue by bondz** [bendiumpope/driver-analysis#1]
Can you add a comment at the top of the functions for analysis and report with the complexity analysis for your function.

You can add something like

```ts
// O(n) time
function report() { ... }
```

**Comment by bondz** [comment]
@bendiumpope

**Comment by bendiumpope** [comment]
I have added the comment indicating the time complexity. Which I found to be Linear time complexity O(n)

**Comment by bendiumpope** [comment]
Good Morning Bond, I have added the time complexity comment to the driver analysis and report but forgot to mail you about it.Thank you.
    On Thursday, February 25, 2021, 04:14:02 PM GMT+1, Bond <notifications@github.com> wrote:  
 
 


Can you add a comment at the top of the functions for analysis and report with the complexity analysis for your function.

You can add something like
// O(n) time
function report() { ... }

**Comment by bondz** [comment]
@bendiumpope No problem. Got the mail. HR should be reaching out to you later today for update.

**Comment by bendiumpope** [comment]
ok bond. Thank you very much

    On Tuesday, March 2, 2021, 11:27:15 AM GMT+1, Bond <notifications@github.com> wrote:  
 
 


@bendiumpope No problem. Got the mail. HR should be reaching out to you later today for update.
